### ISSUE TITLE
Generated files moved to `generated` branch: (404 on /master/generated/pools.json)

### ISSUE THREAD

**Issue by AbelLykens** [bitcoin-data/mining-pools#80]
Maybe pin this issue.
`/master/generated/pools.json` is now on `/generated/pools.json`

Endpoint now is: 
`https://raw.githubusercontent.com/bitcoin-data/mining-pools/generated/pools.json`

**Comment by AbelLykens** [comment]
This can be pinned and closed -- Hope it helps others whose apps broke too since [558308f](https://github.com/bitcoin-data/mining-pools/commit/558308f4bd711b7083d9d64b5ac467b0e4a51f65)

**Comment by AbelLykens** [comment]
cc #79

**Comment by 0xB10C** [comment]
Thanks, will pin this issue. Wasn't aware of your (or any other) dependency on this file. The file location won't change again in the foreseeable future.
